
#include <time.h>		//for time used in random number routines
#include <assert.h>		//for assert

//-------------
//seeds the random number generator from current system time 
//must be called once (beginning of program) 
//so that the numbers generated by the Random function are different every time
void Seed( void) {
	//srand( (unsigned)time( NULL ) );
	srand(256); // seed the generator with the same number each time
}

//-------------
//produces a random number in range [1..max]
//max must be positive
int Random( int max) {
	assert( max > 0);
	return ( rand() % max) + 1;
}
